/* Day - 20. Question: Create a TREND ANALYSIS Showing For Each SERVICE and WEEK: 
WEEK NUMBER, PATIENTS_ADMITTED, Running Total of PATIENTS_ADMITTED (CUMULATIVE), 
3-WEEK Moving AVERAGE of PATINETS_SATISFACTION (Current WEEK and 2 Prior WEEKS), 
and The DIFFERENCE Between CURRENT WEEK ADMISSIONS and The SERVICE AVERAGE. FILTER For WEEKS 10-20 Only. */

-- SOLUTION:
SELECT
	WEEK,
    SERVICE,
    Patients_Admitted,
    SUM(Patients_Admitted) OVER (PARTITION BY SERVICE ORDER BY WEEK) AS RUNNING_TOTAL_ADMITEED,
    ROUND(AVG(Patient_Satisfaction) OVER (PARTITION BY SERVICE ORDER BY WEEK ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 0) AS MOVING_AVG_SATISFACTION,
    ROUND(AVG(Patients_Admitted) OVER (PARTITION By SERVICE), 0) AS AVG_ADMITTED_PER_SERVICE,
    Patients_Admitted - ROUND(AVG(Patients_Admitted) OVER (PARTITION BY SERVICE), 0) AS DIFF_ADMISSIONS_FROM_AVG
FROM SERVICES_WEEKLY
WHERE WEEK BETWEEN 10 AND 20
ORDER BY WEEK, SERVICE;    