
/* Day - 19. Question: For EACH SERVICE, RANK The WEEKS  By PATIENT SATISFACTION SCORE (Highest First). 
Show SERVICE, WEEK, PATIENT_SATISFACTION, PATIENTS_ADMITTED, and The RANK. Include Only The TOP 3 WEEKS Per SERVICE. */




-- FETCH Services_Weekly Table.
SELECT *
FROM SERVICES_WEEKLY;

-- SOLUTION:
SELECT
	SERVICE,
    WEEK,
    PATIENT_SATISFACTION,
    PATIENTS_ADMITTED,
    RANK_Of_The_WEEK
FROM (
	SELECT
		SERVICE,
        WEEK,
        PATIENT_SATISFACTION,
        PATIENTS_ADMITTED,
        RANK() OVER (PARTITION BY SERVICE ORDER BY PATIENT_SATISFACTION DESC) AS RANK_Of_The_WEEK
	FROM SERVICES_WEEKLY
    ) AS RankedResults
    WHERE RANK_Of_The_WEEK <= 3
ORDER BY SERVICE, RANK_Of_The_WEEK;