/* Day - 18. Question: Create a COMPREHENSIVE PERSONNEL and PATIENT List Showing: IDENTIFIER (PATIENT_ID or STAFF_ID), FULL NAME, TYPE ('Patient' or 'Staff'), 
and Associated SERVICE. Include Only Those in 'SURGERY' or 'EMERGENCY' Services. ORDER BY TYPE, Then SERVICE, Then NAME. */

-- SOLUTION: Using UNION.
SELECT
	PATIENT_ID AS IDENTIFIER,
    'Patient' AS TYPE,
    SERVICE,
    NAME AS FULL_NAME
FROM PATIENTS
WHERE SERVICE IN ('SURGERY', 'EMERGENCY')

UNION

SELECT
	STAFF_ID AS IDENTIFIER,
    'Staff' AS TYPE,
    SERVICE,
    STAFF_NAME AS FULL_NAME
FROM STAFF
WHERE SERVICE IN ('SURGERY', 'EMERGENCY')
ORDER BY TYPE, SERVICE, FULL_NAME;

-- SOLUTION: Using UNION ALL.
SELECT
	PATIENT_ID AS IDENTIFIER,
    'Patient' AS TYPE,
    SERVICE,
    NAME AS FULL_NAME
FROM PATIENTS
WHERE SERVICE IN ('SURGERY', 'EMERGENCY')

UNION ALL

SELECT
	STAFF_ID AS IDENTIFIER,
    'Staff' AS TYPE,
    SERVICE,
    STAFF_NAME AS FULL_NAME
FROM STAFF
WHERE SERVICE IN ('SURGERY', 'EMERGENCY')
ORDER BY TYPE, SERVICE, FULL_NAME;