/* Day - 21. Question: Create a Comprehensive HOSPITAL Performance Dashboard Using CTEs. Calculate: 
1) SERVICE-Level Metrics (TOTAL ADMISSIONS, REFUSALS, AVERAGE SATISFACTION), 
2) Staff Metrics Per SERVICE (TOTAL STAFF, AVERAGE WEEKS PRESENT), 
3) Patient Demographics Per SERVICE (AVERAGE AGE, COUNT). 
Then Combine All THREE CTEs To Create a Final Report Showing SERVICE NAME, 
All CALCULATED METRICS, And An Overall PERFORMANCE SCORE (Weighted Average of Admission Rate and Satisfaction). 
ORDER BY Performance Score DESCENDING. */

-- 1) SERVICE-LEVEL METRICS FROM WEEKLY DATA
WITH
SERVICE_METRICS AS (
    SELECT
        SERVICE,
        SUM(PATIENTS_ADMITTED)              AS TOTAL_ADMISSIONS,
        SUM(PATIENTS_REFUSED)               AS TOTAL_REFUSALS,
        AVG(PATIENT_SATISFACTION)           AS AVG_SATISFACTION,
        SUM(PATIENTS_REQUEST)               AS TOTAL_REQUESTS,
        CASE 
            WHEN SUM(PATIENTS_REQUEST) > 0 
                 THEN SUM(PATIENTS_ADMITTED) * 1.0 / SUM(PATIENTS_REQUEST)
            ELSE 0
        END                                 AS ADMISSION_RATE
    FROM SERVICES_WEEKLY
    GROUP BY SERVICE
),

-- 2) STAFF METRICS PER SERVICE
STAFF_METRICS AS (
    SELECT
        S.SERVICE,
        COUNT(DISTINCT S.STAFF_ID)                      AS TOTAL_STAFF,
        AVG(WEEKS_PRESENT)                              AS AVG_WEEKS_PRESENT
    FROM (
        SELECT
            STAFF_ID,
            SERVICE,
            COUNT(DISTINCT WEEK) AS WEEKS_PRESENT
        FROM STAFF_SCHEDULE
        WHERE PRESENT = 1
        GROUP BY STAFF_ID, SERVICE
    ) AS S
    GROUP BY S.SERVICE
),

-- 3) PATIENT DEMOGRAPHICS PER SERVICE
PATIENT_DEMOGRAPHICS AS (
    SELECT
        SERVICE,
        AVG(AGE)                    AS AVG_AGE,
        COUNT(*)                    AS PATIENT_COUNT
    FROM PATIENTS
    GROUP BY SERVICE
),

-- 4) COMBINE ALL METRICS
COMBINED AS (
    SELECT
        SM.SERVICE,
        SM.TOTAL_ADMISSIONS,
        SM.TOTAL_REFUSALS,
        SM.AVG_SATISFACTION,
        SM.TOTAL_REQUESTS,
        SM.ADMISSION_RATE,
        COALESCE(ST.TOTAL_STAFF, 0)        AS TOTAL_STAFF,
        COALESCE(ST.AVG_WEEKS_PRESENT, 0)  AS AVG_WEEKS_PRESENT,
        COALESCE(PD.AVG_AGE, 0)            AS AVG_AGE,
        COALESCE(PD.PATIENT_COUNT, 0)      AS PATIENT_COUNT
    FROM SERVICE_METRICS SM
    LEFT JOIN STAFF_METRICS ST
        ON SM.SERVICE = ST.SERVICE
    LEFT JOIN PATIENT_DEMOGRAPHICS PD
        ON SM.SERVICE = PD.SERVICE
)

-- 5) FINAL DASHBOARD WITH PERFORMANCE SCORE
SELECT
    SERVICE                             AS SERVICE_NAME,
    TOTAL_ADMISSIONS,
    TOTAL_REFUSALS,
    AVG_SATISFACTION,
    TOTAL_REQUESTS,
    ADMISSION_RATE,
    TOTAL_STAFF,
    AVG_WEEKS_PRESENT,
    AVG_AGE,
    PATIENT_COUNT,
    -- EXAMPLE WEIGHTED SCORE: 60% ADMISSION RATE, 40% SATISFACTION (SCALED 0–1)
    (0.6 * ADMISSION_RATE + 0.4 * (AVG_SATISFACTION / 100.0)) AS PERFORMANCE_SCORE
FROM COMBINED
ORDER BY PERFORMANCE_SCORE DESC;

